---
# Checkout
jffortier: 0.5
lemonmade: 0.5

# Admin
dominikwilkowski: 0.125
developit: 0.125
alex-page: 0.125
olavoasantos: 0.125
kyledurand: 0.125
Fionoble: 0.125
vividviolet: 0.125
bratsos: 0.125
# testing
gwyneplaine: 1

# POS
heltisace: 0.5
pkhanal: 0.5
