weight_to_approve: 2.5
min_voters_required: 10

# PR reviews are being distributed to the below people
voters:
  # Checkout; combined weight: 1
  jffortier: 0.5
  lemonmade: 0.5

  # Admin; combined weight: 1
  dominikwilkowski: 0.125
  developit: 0.125
  alex-page: 0.125
  olavoasantos: 0.125
  kyledurand: 0.125
  Fionoble: 0.125
  vividviolet: 0.125
  bratsos: 0.125

  # POS; combined weight: 1
  heltisace: 0.5
  pkhanal: 0.5
