weight_to_approve: 2.5
min_voters_required: 12

# PR reviews are being distributed to the below people
voters:
  # Checkout
  jffortier: 0.5
  lemonmade: 0.5

  # Admin
  dominikwilkowski: 0.125
  developit: 0.125
  alex-page: 0.125
  olavoasantos: 0.125
  kyledurand: 0.125
  Fionoble: 0.125
  vividviolet: 0.125
  bratsos: 0.125

  # POS
  heltisace: 0.5
  pkhanal: 0.5
