name: 'Github Consensus'
author: dominikwilkowski
description: 'Getting consensus on a repo via voting'
inputs:
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    default: ${{ github.token }}
  repository:
    description: "The full name of the repository in which to tally votes."
    default: ${{ github.repository }}
  serverURL:
    description: "URL of github server. You shouldn't need to set this manually."
    default: ${{ github.server_url }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'thumbs-up'
