name: 'PR review'
on: pull_request_review

jobs:
  git-consensus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Evaluate vote
        uses: ./.github/workflows/github-consensus/
