name: 'PR review'
on:
  - pull_request_review
  - pull_request_target

jobs:
  democracy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Evaluate vote
        uses: ./.github/workflows/github-consensus/
